### ISSUE TITLE
"Track is not playable: youtube:video/xxxxx" + pykka._exceptions.ActorDeadError errors with latest build

### ISSUE THREAD

**Issue by ned-kelly** [natumbri/mopidy-youtube#172]
Hi there,

As the title suggest I'm having issues with the latest build of Mopidy + mopidy-youtube for some reason, and it was working a few hours ago which is really strange...

Does anyone have any ideas/pointers how to resolve?

I'm running Mopidy in docker (not that it makes any difference) versions: 

Have tried with both `api_enabled=true` (Using my own Google Cloud Creds) and `api_enabled=false` with no luck ...

### Versions:
```
Mopidy: 3.1.1
Mopidy-YouTube 3.2
gstreamer + plugins & plugins-bad: 1.0
```

### Additional config:
```
threads_max = 40
search_results = 15
playlist_max_videos = 500
```

### Latest crashlog:
```
0|mopidy  | [youtube] XuCa4VsuZNI: Downloading webpage
0|mopidy  | [youtube] XuCa4VsuZNI: Downloading player 1d7f16b4
0|mopidy  | ERROR    2021-04-07 07:38:16,022 [18429:Core-12] mopidy.core.playback
0|mopidy  |   YouTubeBackend backend caused an exception.
0|mopidy  | Traceback (most recent call last):
0|mopidy  |   File "/usr/lib/python3/dist-packages/mopidy/core/playback.py", line 350, in _change
0|mopidy  |     if not backend.playback.change_track(pending_tl_track.track).get():
0|mopidy  |   File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
0|mopidy  |     _compat.reraise(*self._data['exc_info'])
0|mopidy  |   File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
0|mopidy  |     raise value
0|mopidy  |   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
0|mopidy  |     response = self._handle_receive(envelope.message)
0|mopidy  |   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
0|mopidy  |     return callee(*message.args, **message.kwargs)
0|mopidy  |   File "/usr/lib/python3/dist-packages/mopidy/backend.py", line 271, in change_track
0|mopidy  |     download=self.should_download(uri),
0|mopidy  |   File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
0|mopidy  |     _compat.reraise(*self._data['exc_info'])
0|mopidy  |   File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
0|mopidy  |     raise value
0|mopidy  |   File "/usr/lib/python3/dist-packages/pykka/_ref.py", line 107, in ask
0|mopidy  |     raise ActorDeadError('{} not found'.format(self))
0|mopidy  | pykka._exceptions.ActorDeadError: Audio (urn:uuid:338c163c-7e28-4d68-af1c-7e26d6de8d33) not found
0|mopidy  | WARNING  2021-04-07 07:38:16,022 [18429:Core-12] mopidy.core.tracklist
0|mopidy  |   Track is not playable: youtube:video/Diplo Sonny Fodera - Turn Back Time (Official Music Video).XuCa4VsuZNI
```

### Related Packages:

```Mopidy-YouTube==3.2 from git+https://github.com/natumbri/mopidy-youtube.git@release-3.2 in /usr/local/lib/python3.7/dist-packages
beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.2) (4.9.3)
cachetools in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.2) (4.2.1)
Mopidy>=3.1 in /usr/lib/python3/dist-packages (from Mopidy-YouTube==3.2) (3.1.1)
Pykka>=2.0.1 in /usr/lib/python3/dist-packages (from Mopidy-YouTube==3.2) (2.0.3)
requests in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.2) (2.25.1)
setuptools in /usr/lib/python3/dist-packages (from Mopidy-YouTube==3.2) (40.8.0)
youtube_dl>=2020.12.22 in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.2) (2021.4.7)
soupsieve>1.2; python_version >= "3.0" in /usr/local/lib/python3.7/dist-packages (from beautifulsoup4->Mopidy-YouTube==3.2) (2.2.1)
urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->Mopidy-YouTube==3.2) (1.24.1)
certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->Mopidy-YouTube==3.2) (2018.8.24)
chardet<5,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->Mopidy-YouTube==3.2) (3.0.4)
idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests->Mopidy-YouTube==3.2) (2.6)
```

**Comment by christian3107** [comment]
Hello, first try to update `youtube_dl` to latest [v2021.04.07](https://youtube-dl.org/)
```
wget https://youtube-dl.org/downloads/latest/youtube-dl-2021.04.01.tar.gz
python3 -m pip install --upgrade ./youtube-dl-2021.04.01.tar.gz
systemctl restart mopidy
```

**Comment by ned-kelly** [comment]
Already running `2021.04.07` - Sorry forgot to mention that one also...

**Comment by natumbri** [comment]
@christian3107 I'm able to play this with the current version; can you confirm that it is still not working?

**Comment by ned-kelly** [comment]
Turns out it's actually related to gstreamer configuration issues after hours of banging my head against the wall and diffing docker/git commit history ... So sorry to post a non-existant bug .... happy to say it's all working now!!!
