### ISSUE TITLE
exception when adding a video

### ISSUE THREAD

**Issue by solsticedhiver** [natumbri/mopidy-youtube#173]
Whatever syntax I am using, I got an error when attempting to add a youtube video:

```
ERROR    2021-04-15 14:09:52,193 [3:Core-10] mopidy.core.library
  YouTubeBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/lib/python3.9/site-packages/mopidy/core/library.py", line 217, in lookup
    result = future.get()
  File "/usr/lib/python3.9/site-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python3.9/site-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3.9/site-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/lib/python3.9/site-packages/mopidy_youtube/backend.py", line 292, in lookup
    return [self.lookup_video_track(video_id)]
  File "/usr/lib/python3.9/site-packages/mopidy_youtube/backend.py", line 211, in lookup_video_track
    return convert_video_to_track(video, "YouTube Video")
  File "/usr/lib/python3.9/site-packages/mopidy_youtube/backend.py", line 33, in convert_video_to_track
    length=video.length.get() * 1000,
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by natumbri** [comment]
Please try with the current version and reopen if pain persists.  Thanks.
