### ISSUE TITLE
"No data found on page" / "No tracks found..."

### ISSUE THREAD

**Issue by T0MuX** [natumbri/mopidy-youtube#181]
Hi,
I'm using Mopidy v3.1.1 with mopidy-youtube v3.3.r2.g9db86ff-1
The extension is loaded correcly by Mopidy, but I can't search anything on youtube.

On the web interface (mopidy-musicbox v3.1.0-2), it saying "No tracks found...", and in the mopidy's stdout/stderr see below :

```
INFO     2021-05-18 14:34:23,604 [53610:YouTubeBackend-6] mopidy_youtube
  youtube LibraryProvider.search "{'any': ['naruto openings']}"
INFO     2021-05-18 14:34:23,604 [53610:YouTubeBackend-6] mopidy_youtube
  Searching YouTube for query "naruto openings"
INFO     2021-05-18 14:34:23,604 [53610:YouTubeBackend-6] mopidy_youtube
  session.get triggered: search
INFO     2021-05-18 14:34:23,604 [53610:YouTubeBackend-6] mopidy_youtube
  session.get triggered: bs4api run_search
INFO     2021-05-18 14:34:24,506 [53610:YouTubeBackend-6] mopidy_youtube
  nothing in the soup, trying japi
ERROR    2021-05-18 14:34:24,507 [53610:YouTubeBackend-6] mopidy_youtube
  No data found on page
ERROR    2021-05-18 14:34:24,507 [53610:YouTubeBackend-6] mopidy_youtube
  search error "No data found on page"
INFO     2021-05-18 14:34:24,507 [53610:YouTubeBackend-6] pykka
  Exception returned from YouTubeBackend (urn:uuid:8241b5bb-0d98-472b-89fd-eb34af678281) to caller:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pykka/_actor.py", line 186, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3.9/site-packages/pykka/_actor.py", line 286, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/lib/python3.9/site-packages/mopidy_youtube/backend.py", line 177, in search
    playlists = [entry for entry in entries if not entry.is_video]
TypeError: 'NoneType' object is not iterable
WARNING  2021-05-18 14:34:24,507 [53610:Core-8] mopidy.core.library
  YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.
```

Using Archlinux, totally updated, with linux-lts v5.10.37-1-lts

Thank you

**Comment by 7ider5** [comment]
Could be a problem of Google consent cookie, please check here : 
https://github.com/natumbri/mopidy-youtube/issues/170

**Comment by natumbri** [comment]
@T0MuX  is this still a problem?  

If it is, maybe try the [yt-playlists branch](/natumbri/mopidy-youtube/tree/feature/yt-playlists), which has had a bit of work done to it recently?

If not, maybe write something about how you fixed it and close the issue?

Cheers,
Nik

**Comment by T0MuX** [comment]
Hi, sorry for the late.

I updated everything (whole system, and mopidy-youtube), and still have the same issue :

```
INFO     2021-07-23 11:28:44,079 [33764:YouTubeBackend-6] mopidy_youtube
  youtube LibraryProvider.search "{'any': ['battle tapes']}"
INFO     2021-07-23 11:28:44,079 [33764:YouTubeBackend-6] mopidy_youtube
  Searching YouTube for query "battle tapes"
INFO     2021-07-23 11:28:44,079 [33764:YouTubeBackend-6] mopidy_youtube
  session.get triggered: search
INFO     2021-07-23 11:28:44,079 [33764:YouTubeBackend-6] mopidy_youtube
  session.get triggered: bs4api run_search
INFO     2021-07-23 11:28:44,341 [33764:YouTubeBackend-6] mopidy_youtube
  nothing in the soup, trying japi
ERROR    2021-07-23 11:28:44,342 [33764:YouTubeBackend-6] mopidy_youtube
  No data found on page
ERROR    2021-07-23 11:28:44,342 [33764:YouTubeBackend-6] mopidy_youtube
  search error "No data found on page"
INFO     2021-07-23 11:28:44,342 [33764:YouTubeBackend-6] pykka
  Exception returned from YouTubeBackend (urn:uuid:2094864d-1c91-4dca-bee5-3c28043bb40b) to caller:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pykka/_actor.py", line 186, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3.9/site-packages/pykka/_actor.py", line 286, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/lib/python3.9/site-packages/mopidy_youtube/backend.py", line 177, in search
    playlists = [entry for entry in entries if not entry.is_video]
TypeError: 'NoneType' object is not iterable
WARNING  2021-07-23 11:28:44,343 [33764:Core-8] mopidy.core.library
  YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.
```

**Comment by T0MuX** [comment]
Hi, I still have this issue, is it possible to open it again please ?

**Comment by natumbri** [comment]
Sure. I can't replicate the error though, so it will be hard to fix...  Are you able to try with python 3.7 or 3.8?

**Comment by natumbri** [comment]
Reopening

**Comment by natumbri** [comment]
Sure. I can't replicate the error though, so it will be hard to fix... Are you able to try with python 3.7 or 3.8?

**Comment by natumbri** [comment]
@T0MuX try the new [fix/thumbnails](/natumbri/mopidy-youtube/tree/fix/thumbnails).

While I was trying to fix the thumbnail support, I started to get an error a bit like yours. Turns out the format of the data YouTube was sending changed unexpectedly. I fixed it - maybe it will solve your problem?

**Comment by natumbri** [comment]
@T0MuX  am I ok to close this issue?  I've merged everything into [develop](/natumbri/mopidy-youtube/tree/develop).
