### ISSUE TITLE
thumbnails

### ISSUE THREAD

**Issue by natumbri** [natumbri/mopidy-youtube#197]
Trying to tidy up treatment of thumbnails.  @thanxx and @codeasashu, any chance you could test (for youtube API and youtube music, respectively)?

The  branch is [fix/thumbnails](/natumbri/mopidy-youtube/tree/fix/thumbnails).

Any feedback appreciated.

Cheers,
Nik

**Comment by thanxx** [comment]
I am getting errors on this branch with API enabled:
`TypeError: 'Video' object is not iterable`


also, I can't see thumbnails
![image](https://user-images.githubusercontent.com/21316174/127826403-280447fc-2ea5-4b73-857b-d6dfad91e582.png)


```
INFO     2021-07-28 09:07:36,387 [9033:YouTubeBackend-6] mopidy_youtube
  youtube LibraryProvider.lookup "youtube:video:n2htH-vf1VQ"
INFO     2021-07-28 09:07:36,391 [9033:YouTubeBackend-6] mopidy_youtube
  youtube LibraryProvider.lookup "youtube:video:OSC-KiBpu-4"
DEBUG    2021-07-28 09:07:36,397 [9033:Core-7] mopidy.core.tracklist
  Triggering event: tracklist_changed()
DEBUG    2021-07-28 09:07:36,398 [9033:Core-7] mopidy.listener
  Sending tracklist_changed to CoreListener: {}
DEBUG    2021-07-28 09:07:36,404 [9033:HttpServer] mopidy.http.handlers
  Sent WebSocket message to 192.168.1.160: '{"jsonrpc": "2.0", "id": 25, "result": [{"__model__": "TlTrack", "tlid": 1, "track": {"__model__": "Track", "uri": "youtube:video:n2htH-vf1VQ", "name": "\\u4e8c\\u540d\\u6566\\u5b50 \\u200e\\u2013 \\u5824\\u9632 (HQ)", "artists": [{"__model__": "Artist", "name": "Forget The Rock Be Pop"}], "album": {"__model__": "Album", "name": "YouTube Video"}, "length": 266000, "comment": "n2htH-vf1VQ"}}, {"__model__": "TlTrack", "tlid": 2, "track": {"__model__": "Track", "uri": "youtube:video:OSC-KiBpu-4", "name": "Teibo", "artists": [{"__model__": "Artist", "name": "\\u4e8c\\u540d\\u6566\\u5b50 - Topic"}], "album": {"__model__": "Album", "name": "YouTube Video"}, "length": 265000, "comment": "OSC-KiBpu-4"}}]}'
DEBUG    2021-07-28 09:07:36,414 [9033:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.1.160: '{"method":"core.tracklist.filter","params":{"criteria":{"uri":["youtube:video:OSC-KiBpu-4"]}},"jsonrpc":"2.0","id":26}'
DEBUG    2021-07-28 09:07:36,419 [9033:HttpServer] mopidy.http.handlers
  Sent WebSocket message to 192.168.1.160: '{"jsonrpc": "2.0", "id": 26, "result": [{"__model__": "TlTrack", "tlid": 2, "track": {"__model__": "Track", "uri": "youtube:video:OSC-KiBpu-4", "name": "Teibo", "artists": [{"__model__": "Artist", "name": "\\u4e8c\\u540d\\u6566\\u5b50 - Topic"}], "album": {"__model__": "Album", "name": "YouTube Video"}, "length": 265000, "comment": "OSC-KiBpu-4"}}]}'
DEBUG    2021-07-28 09:07:36,422 [9033:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.1.160: '{"method":"core.tracklist.get_tl_tracks","jsonrpc":"2.0","id":27}'
DEBUG    2021-07-28 09:07:36,428 [9033:HttpServer] mopidy.http.handlers
  Sent WebSocket message to 192.168.1.160: '{"jsonrpc": "2.0", "id": 27, "result": [{"__model__": "TlTrack", "tlid": 1, "track": {"__model__": "Track", "uri": "youtube:video:n2htH-vf1VQ", "name": "\\u4e8c\\u540d\\u6566\\u5b50 \\u200e\\u2013 \\u5824\\u9632 (HQ)", "artists": [{"__model__": "Artist", "name": "Forget The Rock Be Pop"}], "album": {"__model__": "Album", "name": "YouTube Video"}, "length": 266000, "comment": "n2htH-vf1VQ"}}, {"__model__": "TlTrack", "tlid": 2, "track": {"__model__": "Track", "uri": "youtube:video:OSC-KiBpu-4", "name": "Teibo", "artists": [{"__model__": "Artist", "name": "\\u4e8c\\u540d\\u6566\\u5b50 - Topic"}], "album": {"__model__": "Album", "name": "YouTube Video"}, "length": 265000, "comment": "OSC-KiBpu-4"}}]}'
DEBUG    2021-07-28 09:07:36,430 [9033:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.1.160: '{"method":"core.tracklist.get_tl_tracks","jsonrpc":"2.0","id":28}'
DEBUG    2021-07-28 09:07:36,436 [9033:HttpServer] mopidy.http.handlers
  Sent WebSocket message to 192.168.1.160: '{"jsonrpc": "2.0", "id": 28, "result": [{"__model__": "TlTrack", "tlid": 1, "track": {"__model__": "Track", "uri": "youtube:video:n2htH-vf1VQ", "name": "\\u4e8c\\u540d\\u6566\\u5b50 \\u200e\\u2013 \\u5824\\u9632 (HQ)", "artists": [{"__model__": "Artist", "name": "Forget The Rock Be Pop"}], "album": {"__model__": "Album", "name": "YouTube Video"}, "length": 266000, "comment": "n2htH-vf1VQ"}}, {"__model__": "TlTrack", "tlid": 2, "track": {"__model__": "Track", "uri": "youtube:video:OSC-KiBpu-4", "name": "Teibo", "artists": [{"__model__": "Artist", "name": "\\u4e8c\\u540d\\u6566\\u5b50 - Topic"}], "album": {"__model__": "Album", "name": "YouTube Video"}, "length": 265000, "comment": "OSC-KiBpu-4"}}]}'
DEBUG    2021-07-28 09:07:36,438 [9033:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.1.160: '{"method":"core.playback.stop","jsonrpc":"2.0","id":29}'
DEBUG    2021-07-28 09:07:36,442 [9033:HttpServer] mopidy.http.handlers
  Sent WebSocket message to 192.168.1.160: '{"jsonrpc": "2.0", "id": 29, "result": null}'
DEBUG    2021-07-28 09:07:36,445 [9033:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.1.160: '{"method":"core.library.get_images","params":{"uris":["youtube:video:n2htH-vf1VQ"]},"jsonrpc":"2.0","id":30}'
INFO     2021-07-28 09:07:36,450 [9033:YouTubeBackend-6] pykka
  Exception returned from YouTubeBackend (urn:uuid:a40f8058-0f54-45fe-906d-fb10aadaf473) to caller:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 186, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 286, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/root/mopidy-youtube/mopidy_youtube/backend.py", line 364, in get_images
    for (uri, video_id) in zip(uris, video_ids)
  File "/root/mopidy-youtube/mopidy_youtube/backend.py", line 365, in <dictcomp>
    if video_id
  File "/root/mopidy-youtube/mopidy_youtube/youtube.py", line 33, in wrapper
    func(self)  # should create the future
  File "/root/mopidy-youtube/mopidy_youtube/youtube.py", line 276, in thumbnails
    requiresThumbnail = self._add_futures(self, "thumbnails")
  File "/root/mopidy-youtube/mopidy_youtube/youtube.py", line 133, in _add_futures
    return list(filter(add, futures_list))
TypeError: 'Video' object is not iterable
ERROR    2021-07-28 09:07:36,453 [9033:Core-7] mopidy.core.library
  YouTubeBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 181, in get_images
    if future.get() is None:
  File "/usr/local/lib/python3.7/dist-packages/pykka/_threading.py", line 55, in get
    raise exc_value
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 186, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 286, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/root/mopidy-youtube/mopidy_youtube/backend.py", line 364, in get_images
    for (uri, video_id) in zip(uris, video_ids)
  File "/root/mopidy-youtube/mopidy_youtube/backend.py", line 365, in <dictcomp>
    if video_id
  File "/root/mopidy-youtube/mopidy_youtube/youtube.py", line 33, in wrapper
    func(self)  # should create the future
  File "/root/mopidy-youtube/mopidy_youtube/youtube.py", line 276, in thumbnails
    requiresThumbnail = self._add_futures(self, "thumbnails")
  File "/root/mopidy-youtube/mopidy_youtube/youtube.py", line 133, in _add_futures
    return list(filter(add, futures_list))
TypeError: 'Video' object is not iterable
DEBUG    2021-07-28 09:07:36,459 [9033:HttpServer] mopidy.http.handlers
  Sent WebSocket message to 192.168.1.160: '{"jsonrpc": "2.0", "id": 30, "result": {"youtube:video:n2htH-vf1VQ": []}}'
DEBUG    2021-07-28 09:07:36,462 [9033:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.1.160: '{"method":"core.playback.get_current_tl_track","jsonrpc":"2.0","id":31}'
DEBUG    2021-07-28 09:07:36,466 [9033:HttpServer] mopidy.http.handlers
  Sent WebSocket message to 192.168.1.160: '{"jsonrpc": "2.0", "id": 31, "result": null}'
DEBUG    2021-07-28 09:07:36,468 [9033:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.1.160: '{"method":"core.library.get_images","params":{"uris":["youtube:video:n2htH-vf1VQ"]},"jsonrpc":"2.0","id":32}'
INFO     2021-07-28 09:07:36,474 [9033:YouTubeBackend-6] pykka
  Exception returned from YouTubeBackend (urn:uuid:a40f8058-0f54-45fe-906d-fb10aadaf473) to caller:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 186, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 286, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/root/mopidy-youtube/mopidy_youtube/backend.py", line 364, in get_images
    for (uri, video_id) in zip(uris, video_ids)
  File "/root/mopidy-youtube/mopidy_youtube/backend.py", line 365, in <dictcomp>
    if video_id
  File "/root/mopidy-youtube/mopidy_youtube/youtube.py", line 33, in wrapper
    func(self)  # should create the future
  File "/root/mopidy-youtube/mopidy_youtube/youtube.py", line 276, in thumbnails
    requiresThumbnail = self._add_futures(self, "thumbnails")
  File "/root/mopidy-youtube/mopidy_youtube/youtube.py", line 133, in _add_futures
    return list(filter(add, futures_list))
TypeError: 'Video' object is not iterable
ERROR    2021-07-28 09:07:36,477 [9033:Core-7] mopidy.core.library
  YouTubeBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 181, in get_images
    if future.get() is None:
  File "/usr/local/lib/python3.7/dist-packages/pykka/_threading.py", line 55, in get
    raise exc_value
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 186, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 286, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/root/mopidy-youtube/mopidy_youtube/backend.py", line 364, in get_images
    for (uri, video_id) in zip(uris, video_ids)
  File "/root/mopidy-youtube/mopidy_youtube/backend.py", line 365, in <dictcomp>
    if video_id
  File "/root/mopidy-youtube/mopidy_youtube/youtube.py", line 33, in wrapper
    func(self)  # should create the future
  File "/root/mopidy-youtube/mopidy_youtube/youtube.py", line 276, in thumbnails
    requiresThumbnail = self._add_futures(self, "thumbnails")
  File "/root/mopidy-youtube/mopidy_youtube/youtube.py", line 133, in _add_futures
    return list(filter(add, futures_list))
TypeError: 'Video' object is not iterable
```

**Comment by natumbri** [comment]
Yeah, thanks @thanxx - I think I have stuffed something up.  I have tried to make a quick fix - please feel free to test it out, if you feel like it.  But I think it may be back to the drawing board with this one, for a more fundamental rethink.

Cheers,
Nik

**Comment by codeasashu** [comment]
@natumbri I use ncmpcpp which doesn't have thumbnail support (or maybe I don't have any idea about it). I'll try some web player to test out the thumbnails in ytmusic

**Comment by natumbri** [comment]
Ok, I made a bunch of improvements; it should work now. And I got distracted by the autoplay functionality, so that might work better (or it, too, might be broken now).

Cheers
Nik

**Comment by natumbri** [comment]
I'm happy that it is working now.  Closing.
