### ISSUE TITLE
Error when searching for videos

### ISSUE THREAD

**Issue by natumbri** [natumbri/mopidy-youtube#20]
From @B3N4K: https://github.com/mopidy/mopidy-youtube/issues/103#issuecomment-496816092

When i have api_enabled = true and i search for videos, i get following exception:

`
2019-05-29 09:03:38,905 INFO [8181:YouTubeBackend-6] mopidy_youtube: youtube LibraryProvider.search "{u'any': [u'danheim']}"
2019-05-29 09:03:38,944 INFO [8181:YouTubeBackend-6] mopidy_youtube: Searching YouTube for query "danheim"
2019-05-29 09:03:39,691 ERROR [8181:Thread-16] mopidy_youtube: youtube thread error: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy_youtube/youtube.py", line 663, in worker
    f(*args)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_youtube/youtube.py", line 203, in job
    video._set_api_data(fields, dict.get(video.id))
  File "/usr/local/lib/python2.7/dist-packages/mopidy_youtube/youtube.py", line 165, in _set_api_data
    + int(m.group('seconds') or 0))
AttributeError: 'NoneType' object has no attribute 'group'
`

I still get the search results though. Then if i add a song to be played, following message will be displayed in logs and whole mopidy will freeze forever:
`2019-05-29 09:03:57,709 INFO [8181:YouTubeBackend-6] mopidy_youtube: youtube LibraryProvider.lookup "youtube:video/Danheim - Ulfhednar.c6MczzFi67M"`

**Comment by natumbri** [comment]
I'll have a look and see if I can replicate.

**Comment by B3N4K** [comment]
After further investigation i can say that this issue is again related to the "live event" type of video (duh). The culprit is https://www.youtube.com/watch?v=jpa64Z004qA.

The parsed metadata at the line 166 (in the exceptiopn above) that are causing the exception are:

```
{u'channelTitle': u'Danheim', u'title': u'Danheim Radio (Live Viking Music Radio - 24/7)'}, u'contentDetails': {u'duration': u'P11W2DT23H55M7S'}, u'id': u'jpa64Z004qA'}
```

Obviously, the regex didnt expect that length could have `11W2D` in there (lol).

So i've fixed the regex with:

```
m = re.search(r'P((?P<weeks>\d+)W)?'
    + r'((?P<days>\d+)D)?'
    + r'T((?P<hours>\d+)H)?'
    + r'((?P<minutes>\d+)M)?'
    + r'((?P<seconds>\d+)S)?',
    item['contentDetails']['duration'])
val = (int(m.group('weeks') or 0) * 604800
    + int(m.group('days') or 0) * 86400
    + int(m.group('hours') or 0) * 3600
    + int(m.group('minutes') or 0) * 60
    + int(m.group('seconds') or 0))
```

Btw it would be pretty damn cool if it would be possible to filter out this stuff - i certainly don't see anyone listening to 11 weeks long track and the track length also [looks kinda funny](https://i.imgur.com/ej8PHUt.png).

Again, sorry i can't make PR. Thanks for the great work on the repo! Really like it (now that it's working for me). Thanks and keep up the good work!

**Comment by natumbri** [comment]
Thanks. I'll put the new regex in, but I'll leave this issue open to remind me to think about filtering it out - track length really is irrelevant for this kind of thing.

**Comment by natumbri** [comment]
Should be fixed - @B3N4K please let me know...

**Comment by B3N4K** [comment]
Yep, can confirm, the issue is resolved with the latest commits in the `feature/proxy` branch. Thanks a lot!
