### ISSUE TITLE
Cannot uninstall Mopidy-youtube

### ISSUE THREAD

**Issue by Mikka123T** [natumbri/mopidy-youtube#212]
there is an issue with the plugin. It started to use cca 1.6M bandwith even when not used (the servers connected to are Google servers). It helped to uninstall the plugin (network usage dropped to 0), I then installed mopidy-youtube again and the issue (1.6M constant download from google) apeared again. Now I cannot unistall Mopidy-youtube plugin. Here is error message 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.7/shutil.py", line 563, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/usr/local/lib/python3.7/dist-packages/Mopidy_YouTube-3.3.dist-info/INSTALLER' -> '/tmp/pip-uninstall-tlk7n3n0/usr/local/lib/python3.7/dist-packages/Mopidy_YouTube-3.3.dist-info/INSTALLER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/uninstall.py", line 75, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 683, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_uninstall.py", line 224, in remove
    renames(path, new_path)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 280, in renames
    shutil.move(old, new)
  File "/usr/lib/python3.7/shutil.py", line 578, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/Mopidy_YouTube-3.3.dist-info/INSTALLER'

**Comment by Mikka123T** [comment]
As being a non programmer, I forgot to use sudo in from. Appologies for this stupid post.
