### ISSUE TITLE
Error adding youtube URLs

### ISSUE THREAD

**Issue by klundry** [natumbri/mopidy-youtube#224]
Steps I've done: 
Install mopiidy-youtube
Install yt-dlp
Install gstreamer1.0-plugins-bad

My relevant config section is this:
```
[youtube]
enabled = true
youtube_dl_package = yt-dlp
youtube_api_key = ******************************
api_enabled = true
```

Any time I try to add a youtube URL I get this:
```
mpc add yt:https://www.youtube.com/watch?v=1kCLOir0YCs
error adding yt:https://www.youtube.com/watch?v=1kCLOir0YCs: directory or file not found
```

Can't figure out what I'm doing wrong.

**Comment by natumbri** [comment]
Try `youtube_dl_package = yt_dlp` in your config.

**Comment by klundry** [comment]
No change. Get the same error with yt_dlp.

**Comment by natumbri** [comment]
Well, that was the only obvious problem with your config.  Is there anything revealed in the log file? Usually found at `/var/log/mopidy/mopidy.log`. I'd be looking at start up messages, and anything that comes up when you try to add the track.

**Comment by klundry** [comment]
Ok, found this in the log.

```
Feb 04 18:57:42 musicidy mopidy[31801]: INFO     [MainThread] mopidy.__main__ Enabled extensions: stream, softwaremixer, muse, local, http, m3u, file, youtube, podcast, mpd, internetarchive
Feb 04 18:57:42 musicidy mopidy[31801]: INFO     [MainThread] mopidy.__main__ Disabled extensions: none
Feb 04 18:57:42 musicidy mopidy[31801]: ERROR    [MainThread] mopidy.__main__ Extension youtube failed during setup. This might have left the registry in a bad state.
Feb 04 18:57:42 musicidy mopidy[31801]: Traceback (most recent call last):
Feb 04 18:57:42 musicidy mopidy[31801]:   File "/usr/lib/python3/dist-packages/mopidy/__main__.py", line 129, in main
Feb 04 18:57:42 musicidy mopidy[31801]:     extension.setup(registry)
Feb 04 18:57:42 musicidy mopidy[31801]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/__init__.py", line 39, in setup
Feb 04 18:57:42 musicidy mopidy[31801]:     from .backend import YouTubeBackend, YouTubeCoreListener
Feb 04 18:57:42 musicidy mopidy[31801]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/backend.py", line 10, in <module>
Feb 04 18:57:42 musicidy mopidy[31801]:     from mopidy_youtube.apis import youtube_api, youtube_japi, youtube_music
Feb 04 18:57:42 musicidy mopidy[31801]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/apis/youtube_music.py", line 7, in <module>
Feb 04 18:57:42 musicidy mopidy[31801]:     from ytmusicapi import YTMusic
Feb 04 18:57:42 musicidy mopidy[31801]: ModuleNotFoundError: No module named 'ytmusicapi'
Feb 04 18:57:43 musicidy mopidy[31801]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Feb 04 18:57:43 musicidy mopidy[31801]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: FileBackend, M3UBackend, StreamBackend, PodcastBackend, LocalBackend, InternetArchive
```

**Comment by natumbri** [comment]
Yep, that's the problem - I should change it so `ytmusicapi` is only imported if you want to use the YouTube Music API. If you don't want to wait for the fix, you could just install the `ytmusicapi` package, for example, by running `python3 -m pip install --upgrade ytmusicapi` (depending on your system; you may also need to do it as superuser).

**Comment by natumbri** [comment]
I pushed a new commit to the `develop` branch.  If you're able to install from github, it should be fixed.  On a unixy system, you should be able to install from github by running something like:
```
python3 -m pip install https://github.com/natumbri/mopidy-youtube/archive/develop.zip
```
Depending on how your unixy system is configured, you may need to install as superuser (eg, using `sudo`).

Give it a try; let me know if it is fixed.

Thanks,
Nik

**Comment by klundry** [comment]
Thanks! I will give it a try later and let you know.

**Comment by klundry** [comment]
It works!

**Comment by hadwinwen** [comment]
@natumbri  Hi,when i add youtube url via mpd client, I get same error.How can I fix it
I tried to reinstall mopidy-youtube
```
python3 -m pip install https://github.com/natumbri/mopidy-youtube/archive/develop.zip
```

Here is my modipy.conf
```
[youtube]
enabled = true
allow_cache = true
youtube_api_key = API_KEY
api_enabled = true
autoplay_enabled = true
youtube_dl_package = yt_dlp
```

Mopidy startup log
```
Feb 14 03:30:09 1494703820hax.localdomain systemd[1]: Starting Mopidy music server...
Feb 14 03:30:09 1494703820hax.localdomain systemd[1]: Started Mopidy music server.
Feb 14 03:30:10 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.1.1
Feb 14 03:30:10 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
Feb 14 03:30:10 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
Feb 14 03:30:10 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
Feb 14 03:30:10 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy.config Loading config from command line options
Feb 14 03:30:11 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy.__main__ Enabled extensions: softwaremixer, m3u, mobile, file, mpd, http, stream, youtube
Feb 14 03:30:11 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy.__main__ Disabled extensions: ytmusic
Feb 14 03:30:11 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Feb 14 03:30:11 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Feb 14 03:30:11 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: YouTubeBackend, FileBackend, M3UBackend, StreamBackend
Feb 14 03:30:11 1494703820hax.localdomain mopidy[74035]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! filesink location=/tmp/snapfifo"
Feb 14 03:30:11 1494703820hax.localdomain mopidy[74035]: INFO     [YouTubeBackend-3] mopidy_youtube file caching enabled (at /var/cache/mopidy/youtube)
Feb 14 03:30:13 1494703820hax.localdomain mopidy[74035]: INFO     [YouTubeBackend-3] mopidy_youtube YouTube API key verified
Feb 14 03:30:13 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Feb 14 03:30:13 1494703820hax.localdomain mopidy[74035]: INFO     [Core-7] mopidy.core.actor Loading state from /var/lib/mopidy/core/state.json.gz
Feb 14 03:30:13 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: YouTubeAutoplayer, YouTubeCoreListener, HttpFrontend, MpdFrontend
Feb 14 03:30:13 1494703820hax.localdomain mopidy[74035]: INFO     [HttpFrontend-11] mopidy.http.actor HTTP server running at [::ffff:127.0.0.1]:6680
Feb 14 03:30:13 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy_mpd.actor MPD server running at [::]:6600
Feb 14 03:30:13 1494703820hax.localdomain mopidy[74035]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
```

When I add youtue url via mpd client:
client command:
```
mpc add https://www.youtube.com/watch?v=9vodga3_Nog
```

server log:
```
Feb 14 03:51:37 1494703820hax.localdomain mopidy[74193]: INFO     [MpdSession-15] mopidy_mpd.session New MPD connection from [2409:8a55:f1aa:c3c0:a748:3598:5fb:5744]:55250
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]: ERROR    [Core-7] mopidy.core.library StreamBackend backend caused an exception.
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]: Traceback (most recent call last):
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:     yield
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 217, in lookup
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:     result = future.get()
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:   File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:     _compat.reraise(*self._data['exc_info'])
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:   File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:     raise value
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:     response = self._handle_receive(envelope.message)
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:     return callee(*message.args, **message.kwargs)
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:   File "/usr/lib/python3/dist-packages/mopidy/stream/actor.py", line 66, in lookup
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:     _, scan_result = _unwrap_stream(
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:   File "/usr/lib/python3/dist-packages/mopidy/stream/actor.py", line 138, in _unwrap_stream
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:     scan_result = scanner.scan(uri, timeout=scan_timeout)
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:   File "/usr/lib/python3/dist-packages/mopidy/audio/scan.py", line 66, in scan
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:     pipeline, signals = _setup_pipeline(uri, self._proxy_config)
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:   File "/usr/lib/python3/dist-packages/mopidy/audio/scan.py", line 83, in _setup_pipeline
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]:     src = Gst.Element.make_from_uri(Gst.URIType.SRC, uri)
Feb 14 03:51:40 1494703820hax.localdomain mopidy[74193]: gi.repository.GLib.GError: gst-uri-error-quark: No URI handler for the enumerable protocol found (0)
```

**Comment by kingosticks** [comment]
> mpc add https://www.youtube.com/watch?v=9vodga3_Nog

mpc add yt:https://www.youtube.com/watch?v=9vodga3_Nog

**Comment by natumbri** [comment]
Thanks @kingosticks

**Comment by hadwinwen** [comment]
@kingosticks @natumbri 
It's ok,thank you
