### ISSUE TITLE
AttributeError: module 'tornado.gen' has no attribute 'Task'

### ISSUE THREAD

**Issue by 9acca9** [natumbri/mopidy-youtube#238]
Im getting this error:

```
mopidy[30379]: [youtube] IXNrM3PTIZ0: Downloading webpage
mopidy[30379]: [download] Destination: /var/cache/mopidy/youtube/IXNrM3PTIZ0.webm
mopidy[30379]: [788B blob data]
mopidy[30379]: ERROR    [HttpServer] tornado.application Uncaught exception GET /youtube/IXNrM3PTIZ0.webm (127.0.0.1)
mopidy[30379]: HTTPServerRequest(protocol='http', host='localhost:6680', method='GET', uri='/youtube/IXNrM3PTIZ0.webm', version='HTTP/1.1', remote_ip='127.0.0.1')
mopidy[30379]: Traceback (most recent call last):
mopidy[30379]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1704, in _execute
mopidy[30379]:     result = await result
mopidy[30379]:   File "/usr/lib/python3/dist-packages/tornado/gen.py", line 234, in wrapper
mopidy[30379]:     yielded = ctx_run(next, result)
mopidy[30379]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_youtube/web.py", line 100, in get
mopidy[30379]:     yield tornado.gen.Task(self.flush)
mopidy[30379]: AttributeError: module 'tornado.gen' has no attribute 'Task'
mopidy[30379]: ERROR    [HttpServer] tornado.general Cannot send error response after headers written
mopidy[30379]: ERROR    [HttpServer] tornado.general Failed to flush partial response
mopidy[30379]: Traceback (most recent call last):
mopidy[30379]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1704, in _execute
mopidy[30379]:     result = await result
mopidy[30379]:   File "/usr/lib/python3/dist-packages/tornado/gen.py", line 234, in wrapper
mopidy[30379]:     yielded = ctx_run(next, result)
mopidy[30379]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_youtube/web.py", line 100, in get
mopidy[30379]:     yield tornado.gen.Task(self.flush)
mopidy[30379]: AttributeError: module 'tornado.gen' has no attribute 'Task'
mopidy[30379]: During handling of the above exception, another exception occurred:
mopidy[30379]: Traceback (most recent call last):
mopidy[30379]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1204, in send_error
mopidy[30379]:     self.finish()
mopidy[30379]:   File "/usr/lib/python3/dist-packages/tornado/web.py", line 1158, in finish
mopidy[30379]:     self.request.connection.finish()
mopidy[30379]:   File "/usr/lib/python3/dist-packages/tornado/http1connection.py", line 511, in finish
mopidy[30379]:     raise httputil.HTTPOutputError(
mopidy[30379]: tornado.httputil.HTTPOutputError: Tried to write 16877411 bytes less than Content-Length

```

**Comment by natumbri** [comment]
When?

**Comment by kingosticks** [comment]
It's probably https://www.tornadoweb.org/en/stable/releases/v6.0.0.html#tornado-gen (also see https://www.tornadoweb.org/en/stable/releases/v5.0.0.html#tornado-gen)

BUT, if you are going to report an error, at least provide version numbers and context. This is a very unhelpful bug report.

**Comment by natumbri** [comment]
Thanks @kingosticks , and apologies @9acca9 for my abrupt response - as Nick says, it is difficult to deal with bug reports that don't include a bit of context, which can be frustrating.

But it does look like I have some things to look into, so thanks for raising the issue.

Cheers
Nik

**Comment by 9acca9** [comment]
Oh, sorry. I was very tired and don't notice that I was not writing the context when create the post.

Thanks for all your work.

**Comment by nbx3** [comment]
I've been getting this after upgrading recently. Python 3.9.2, Mopidy 3.4.1, Mopidy-YouTube 3.6.1 and yt-dlp 2023.2.17


```
Feb 21 18:09:42 hn mopidy[4816]: INFO     2023-02-21 18:09:42,662 [4817:HttpServer] mopidy_youtube.web
Feb 21 18:09:42 hn mopidy[4816]:   started serving KlTMTxhz9Kg.webm to gstreamer
Feb 21 18:09:42 hn mopidy[4816]: ERROR    2023-02-21 18:09:42,856 [4817:HttpServer] tornado.application
Feb 21 18:09:42 hn mopidy[4816]:   Uncaught exception GET /youtube/KlTMTxhz9Kg.webm (127.0.0.1)
Feb 21 18:09:42 hn mopidy[4816]: HTTPServerRequest(protocol='http', host='localhost:6680', method='GET', uri='/youtube/KlTMTxhz9Kg.webm', version='HTTP/1.1', remote_ip='127.0.0.1')
Feb 21 18:09:42 hn mopidy[4816]: Traceback (most recent call last):
Feb 21 18:09:42 hn mopidy[4816]:   File "/usr/local/lib/python3.9/dist-packages/tornado/web.py", line 1713, in _execute
Feb 21 18:09:42 hn mopidy[4816]:     result = await result
Feb 21 18:09:42 hn mopidy[4816]:   File "/usr/local/lib/python3.9/dist-packages/tornado/gen.py", line 234, in wrapper
Feb 21 18:09:42 hn mopidy[4816]:     yielded = ctx_run(next, result)
Feb 21 18:09:42 hn mopidy[4816]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_youtube/web.py", line 100, in get
Feb 21 18:09:42 hn mopidy[4816]:     yield tornado.gen.Task(self.flush)
Feb 21 18:09:42 hn mopidy[4816]: AttributeError: module 'tornado.gen' has no attribute 'Task'
Feb 21 18:09:42 hn mopidy[4816]: ERROR    2023-02-21 18:09:42,857 [4817:HttpServer] tornado.general
Feb 21 18:09:42 hn mopidy[4816]:   Cannot send error response after headers written

```

**Comment by natumbri** [comment]
Thanks @nbx3 for prompting me on this; I'd completely forgotten about it, and have been busy with other things. I'll bump it up my to-do list...

Cheers
Nik

**Comment by SuperSandro2000** [comment]
Maybe fixed by https://github.com/natumbri/mopidy-youtube/commit/0a069b75716bddfc849492c3df9f450fa4563c61 ?

**Comment by natumbri** [comment]
Hi - yes, I think it is fixed by that one. I just haven't had a chance to test it or push it out to pypi.

I'll see if I can do it today... Hopefully it is actually fixed!

**Comment by SuperSandro2000** [comment]
I did some basic testing and playing youtube videos now works.

**Comment by natumbri** [comment]
OK, on the strength of that testing, I've pushed a new release - thanks!  If it comes back, reopen please.
