### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by BrainStone** [natumbri/mopidy-youtube#27]
Hi there.

I'm sorry if this is a real beginner question. But I would like to try this out instead of the official plugin.  
So how could I install this instead/over the offical plugin?

**Comment by natumbri** [comment]
That's actually a really good question. I don't know how to package things up to make installation easy.

What I would suggest you try is:
- install the official version
- work out where files for the official  version are (maybe with the command: pip show Mopidy-YouTube)
- download the files from my repository (https://github.com/natumbri/mopidy-youtube/tree/feature/revise-API-implementation/mopidy_youtube). You need __init__.py, youtube.py, and backend.py.

- copy them into the location where the official version is (replacing the official files that exist)

See how you go with that - if you try that and it doesn't work, maybe we can work from there.

**Comment by BrainStone** [comment]
Which `youtube.py`?
I can only find those files: https://github.com/natumbri/mopidy-youtube/tree/develop/mopidy_youtube

**Comment by BrainStone** [comment]
P.P.S.: Looks like feature/proxy is the branch you keep merging everything back into. So that's the one I picked. And it seems to work.

Now I also had to install `cachetools`. Not that big of a problem, but worth noting I think.

And the ext.conf also needs to exist as that is the one that provides the defaults.

**Comment by natumbri** [comment]
OK, good point re conf.ext

The branch I'd suggest is the one I linked to - revise-API-implementation - that is the most advanced version. The one you chose - feature/proxy - is pretty up-to-date, also.

I really have basically no idea what I'm doing, and haven't tested this apart from by using it myself, so there are likely bugs and I'll be grateful for your feedback!

Are you using an API key?

**Comment by BrainStone** [comment]
No am not. That's why I wanted it in the first place.

And apparently I'm blind.

**Comment by denkomanceski** [comment]
Maybe creating a new Mopidy plugin which would be named "Mopidy-YoutubeV3" or something would make it easier

**Comment by denkomanceski** [comment]
I managed to replace the official files with yours, updated the config, added the missing packages (cachetools + one more). Now im getting some other error which im not sure if its related with this plugin or not

```INFO     Starting Mopidy 2.2.3
INFO     Loading config from builtin defaults
INFO     Loading config from /home/pi/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mpd, http, stream, m3u, youtube, softwaremixer, file, local
INFO     Disabled extensions: none
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend, YouTubeBackend
INFO     Audio output set to "autoaudiosink"
ERROR    Got un-handled exception from StreamBackend
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 237, in _actor_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 386, in start_backends
    config=config, audio=audio).proxy()
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 94, in start
    obj = cls(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mopidy/stream/actor.py", line 31, in __init__
    stream.Extension.dist_name, stream.Extension.version))
  File "/usr/lib/python2.7/dist-packages/mopidy/internal/http.py", line 17, in get_requests_session
    session = requests.Session()
  File "/home/pi/.local/lib/python2.7/site-packages/requests_cache/core.py", line 212, in __init__
    **backend_options
  File "/home/pi/.local/lib/python2.7/site-packages/requests_cache/core.py", line 73, in __init__
    self.cache = backends.create_backend(backend, cache_name, backend_options)
  File "/home/pi/.local/lib/python2.7/site-packages/requests_cache/backends/__init__.py", line 63, in create_backend
    return registry[backend_name](cache_name, **options)
  File "/home/pi/.local/lib/python2.7/site-packages/requests_cache/backends/sqlite.py", line 28, in __init__
    self.responses = DbPickleDict(location + extension, 'responses', fast_save=fast_save)
  File "/home/pi/.local/lib/python2.7/site-packages/requests_cache/backends/storage/dbdict.py", line 62, in __init__
    with self.connection() as con:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/pi/.local/lib/python2.7/site-packages/requests_cache/backends/storage/dbdict.py", line 74, in connection
    con = sqlite.connect(self.filename)
OperationalError: unable to open database file
INFO     Loaded 0 local tracks using json
INFO     Using scrAPI
ERROR    Unhandled exception in YouTubeBackend (urn:uuid:dffc3a61-71e5-4029-af86-2d1e61394502):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
  File "/usr/lib/python2.7/dist-packages/mopidy_youtube/backend.py", line 87, in on_start
    youtube.Entry.api = youtube.scrAPI(proxy, headers)
  File "/usr/lib/python2.7/dist-packages/mopidy_youtube/youtube.py", line 357, in __init__
    self._create_session(proxy, headers)
  File "/usr/lib/python2.7/dist-packages/mopidy_youtube/youtube.py", line 369, in _create_session
    cls.session = session or requests.Session()
  File "/home/pi/.local/lib/python2.7/site-packages/requests_cache/core.py", line 212, in __init__
    **backend_options
  File "/home/pi/.local/lib/python2.7/site-packages/requests_cache/core.py", line 73, in __init__
    self.cache = backends.create_backend(backend, cache_name, backend_options)
  File "/home/pi/.local/lib/python2.7/site-packages/requests_cache/backends/__init__.py", line 63, in create_backend
    return registry[backend_name](cache_name, **options)
  File "/home/pi/.local/lib/python2.7/site-packages/requests_cache/backends/sqlite.py", line 28, in __init__
    self.responses = DbPickleDict(location + extension, 'responses', fast_save=fast_save)
  File "/home/pi/.local/lib/python2.7/site-packages/requests_cache/backends/storage/dbdict.py", line 62, in __init__
    with self.connection() as con:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/pi/.local/lib/python2.7/site-packages/requests_cache/backends/storage/dbdict.py", line 74, in connection
    con = sqlite.connect(self.filename)
OperationalError: unable to open database file
ERROR    Actor died: YouTubeBackend (urn:uuid:dffc3a61-71e5-4029-af86-2d1e61394502) stopped before handling the message
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend```

**Comment by natumbri** [comment]
Hi @denkomanceski - I think I know what's caused that; and I know how to fix it - it's to do with the location of cache files. I'll get to it today hopefully after work.

**Comment by natumbri** [comment]
Ok - should be fixed and should work fine without root.

**Comment by fran1987** [comment]
I just successfully installed via pip: 
`sudo pip install https://github.com/natumbri/mopidy-youtube/archive/develop.zip`

**Comment by natumbri** [comment]
@fran1987 thank for mentioning using pip, and glad to hear it works!

**Comment by BrainStone** [comment]
You could add that to the docs/README.
