### ISSUE TITLE
Search isn't working

### ISSUE THREAD

**Issue by spacekookie** [natumbri/mopidy-youtube#95]
Hey, I hope this plugin is still being maintained. I'm running `mopidy v2.1.0` with the youtube plugin version `2.0.0`, using the `Mopidy-MusicBox-Webclient v2.5.0`.

I can select youtube as a backend to search, but when I start a search, nothing more happens. The UI just hangs and this appears in the logs:

```
2018-06-22 12:26:53,818 INFO [2011:YouTubeBackend-8] mopidy_youtube: Searching YouTube for query 'Alle Farben'
2018-06-22 12:26:53,825 INFO [2011:YouTubeBackend-8] urllib3.connectionpool: Resetting dropped connection: www.googleapis.com
```

Any advice how to get this to work?

**Comment by kingosticks** [comment]
See https://github.com/mopidy/mopidy-youtube/issues/92

**Comment by Leolamlao** [comment]
How do I remove this if it's no longer work?

**Comment by Leolamlao** [comment]
ERROR    Extension youtube failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/home/pi/.local/lib/python2.7/site-packages/mopidy/__main__.py", line 121, in main
    extension.setup(registry)
  File "/home/pi/.local/lib/python2.7/site-packages/mopidy_youtube/__init__.py", line 29, in setup
    from .backend import YouTubeBackend
  File "/home/pi/.local/lib/python2.7/site-packages/mopidy_youtube/backend.py", line 14, in <module>
    import pafy
  File "/home/pi/.local/lib/python2.7/site-packages/pafy/__init__.py", line 7, in <module>
    from .pafy import new
  File "/home/pi/.local/lib/python2.7/site-packages/pafy/pafy.py", line 52, in <module>
    "pafy: youtube-dl not found; you can use the internal backend by "
ImportError: pafy: youtube-dl not found; you can use the internal backend by setting the environmental variable PAFY_BACKEND to "internal". It is not enabled by default because it is not as well maintained as the youtube-dl backend.

I keep getting this error. How do i remove or fix it?
