### ISSUE TITLE
Search isn't working (YoutubeBackend)

### ISSUE THREAD

**Issue by PelegPLT** [natumbri/mopidy-youtube#97]
INFO     Searching Youtube for query 'me'
ERROR    YoutubeBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 347, in search
    result = future.get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy_youtube/backend.py", line 181, in search
    tracks=search_youtube(search_query)
  File "/usr/lib/python2.7/dist-packages/mopidy_youtube/backend.py", line 90, in search_youtube
    resolve_pool = ThreadPool(processes=16)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 727, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/dummy/__init__.py", line 75, in start
    threading.Thread.start(self)
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

**Comment by zioalex** [comment]
Same problem here

**Comment by CkuT** [comment]
As a temporary workaround, you can install @natumbri awesome work (It does work on my RPi)

```bash
$ sudo pip install https://github.com/natumbri/mopidy-youtube/archive/feature/implement-scrAPI.zip
```

The search is fast, but the song seems to start at the end of the youtube-dl download, which takes several seconds to process.

**Comment by natumbri** [comment]
Thanks @CkuT - I'm glad it works for you! It is hard to know if anyone else uses it (or would be interested in using it). If people do find it worthwhile, hopefully someone will one day merge it into the official code. I did think about trying to become a maintainer for the repo, but I don't think my coding skills are up to the task.
